### ISSUE TITLE
8x8 sub 6GHz MIMO example?

### ISSUE THREAD

**Issue by liubenyuan** [rafaruizortiz/MIMORPH#1]
Hi, I found that in the readme there metioned a 8x8 MIMO sub-6GHz usage, is there an example project on this setting?

**Comment by rafaruizortiz** [comment]
Hi! Let me check if I have a clean and stable version and if you are interested I can upload it.

**Comment by liubenyuan** [comment]
@rafaruizortiz yeah I am surely interested in that :)

**Comment by liubenyuan** [comment]
> Hi! Let me check if I have a clean and stable version and if you are interested I can upload it.

any update?

**Comment by rafaruizortiz** [comment]
There you have it, sorry for the delay!

**Comment by liubenyuan** [comment]
Thank you! I will grab it and test on my board.
